config/routes.rb
ScriptRunner::Engine.routes.draw do
  resources :jobs, only: %i(index new create)
  root to: 'jobs#index'
end

app/models/script_runner/application_record.rb
module ScriptRunner
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/script_runner/job.rb
module ScriptRunner
  class Job < ApplicationRecord
  end
end

app/controllers/script_runner/application_controller.rb
module ScriptRunner
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/script_runner/jobs_controller.rb
require_dependency "script_runner/application_controller"

module ScriptRunner
  class JobsController < ApplicationController
    ScriptRunner.config.jobs_path.each { |path|
      Dir[path.join('**', '*.rb')].each { |x| require x }
    }

    before_action :set_job, only: [:show, :edit, :update, :destroy]

    # GET /jobs
    def index
      @jobs = ApplicationJob.descendants.reject { |x| x == RunScriptJob }
    end

    # GET /jobs/new
    def new
      @jobs = ApplicationJob.descendants.reject { |x| x == RunScriptJob }
    end

    # POST /jobs
    def create
      current_user = send(ScriptRunner.config.current_user_method) || OpenStruct.new(id: nil)
      RunScriptJob.perform_later(current_user.id, job_params.to_s, job_params)
      redirect_to jobs_path, notice: 'Job succesffully enqueued'
    end

    private

    def job_params
      params.fetch(:job, {})
    end
  end
end

app/helpers/script_runner/application_helper.rb
module ScriptRunner
  module ApplicationHelper
  end
end

app/helpers/script_runner/jobs_helper.rb
module ScriptRunner
  module JobsHelper
  end
end

app/views/layouts/script_runner/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Script runner</title>
  <%= stylesheet_link_tag    "script_runner/application", media: "all" %>
  <%= javascript_include_tag "script_runner/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/script_runner/jobs/_argument.html.erb
<div class='argument'>
  <%= text_field_tag :argument =%>
</div>

<div class='key_value_argument'>
  <%= text_field_tag :key =%>
  <%= text_field_tag :value =%>
</div>

<%= link_to "Add Argument", "#", class: "add_argument" %>
<%= link_to "Add Key Value Argument", "#", class: "add_key_value_argument" %>
<%= link_to "Delete Argument", "#" %>

app/views/script_runner/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td> <%= job %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/script_runner/jobs/new.html.erb
<h1><%= t('script_runner.new') %></h1>

<%= form_tag(jobs_path, method: :post) do %>
  <%= select_tag :job, options_for_select(@jobs) %>
  <div class="actions">
    <%= submit_tag t('script_runner.submit') %>
  </div>

  <%=
    #render partial: 'argument'
   %>

<% end %>

<%= link_to 'Back', jobs_path %>